#!/bin/sh

set -e

lb config noauto \
	--architectures i386 \
	--linux-flavours 686-pae \
	--archive-areas "main contrib non-free" \
	--bootappend-live "\
boot=live components \
nox11autologin \
locales=ja_JP.UTF-8,en_US.UTF-8 \
utc=no \
timezone=Asia/Tokyo \
keyboard-model=pc105 \
keyboard-layouts=jp,us \
"\
	"${@}"
